### ISSUE TITLE
LoadError: FreeType library could not be found on macOS

### ISSUE THREAD

**Issue by wgreenr** [JuliaGraphics/FreeType.jl#17]
Got the following while building FreeType (Julia 0.5, macOS Sierra) :

INFO: Building FreeType
==============================[ ERROR: FreeType ]===============================

LoadError: FreeType library could not be found. Please file an issue here: https://github.com/jhasse/FreeType.jl/issues/new
while loading /Users/igor/.julia/FreeType/deps/build.jl, in expression starting on line 18

Homebrew tells me that freetype-2.6_1 already installed, maybe someone could help?

**Comment by Gnimuc** [comment]
which Homebew? `Homebrew` or `Homebrew.jl`?  what's the result of:

```
using Homebrew
Homebrew.installed("FreeType") 
```

**Comment by wgreenr** [comment]
First it was **false**, then I did Homebrew.install(["FreeType"]), now it is 

``` julia
Pkg.installed("FreeType")
v"1.1.0"
```

but the error persists.

**Comment by samuelpowell** [comment]
I have the same error with a fresh installation of Julia 0.5 on 10.12.2.

**Comment by Gnimuc** [comment]
@samuelpowell you should manually install freetype, if you are using `homebrew`, run `brew install freetype` in the **Terminal**. That's because FreeType.jl doesn't use `Homebrew.jl` to automatically download freetype for you.

**Comment by samuelpowell** [comment]
Thanks @Gnimuc, #18 resolves the issue for me.
