### ISSUE TITLE
Backport for Julia v0.6.4?

### ISSUE THREAD

**Issue by rickhg12hs** [JuliaGraphics/FreeType.jl#29]
Could commit 3eefba510f07d34ccc60a753fa83217fe3309644 be backported for Julia v0.6.4 compatibility? Currently, `Makie` can't build on Julia v0.6.4 because `Freetype.jl` can find the tarball to download.

```julia
julia> Pkg.build("FreeType")
INFO: Building FreeType
Info: Downloading https://github.com/Gnimuc/FreeTypeBuilder/releases/download/v2.9/FreeType2.x86_64-linux-gnu.tar.gz to /home/rick/.julia/v0.6/FreeType/deps/usr/downloads/FreeType2.x86_64-linux-gnu.tar.gz...
[21:55:42] 
[21:55:42] curl: (6) Could not resolve host: github.com
=================================================[ ERROR: FreeType ]==================================================

LoadError: Could not download https://github.com/Gnimuc/FreeTypeBuilder/releases/download/v2.9/FreeType2.x86_64-linux-gnu.tar.gz to /home/rick/.julia/v0.6/FreeType/deps/usr/downloads/FreeType2.x86_64-linux-gnu.tar.gz
while loading /home/rick/.julia/v0.6/FreeType/deps/build.jl, in expression starting on line 30

======================================================================================================================

===================================================[ BUILD ERRORS ]===================================================

WARNING: FreeType had build errors.

 - packages with build errors remain installed in /home/rick/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("FreeType")`
 - build a single package by running its `deps/build.jl` script

======================================================================================================================

```

**Comment by Gnimuc** [comment]
I'll look into this, a quick fix would be pinning Freetype.jl at  v1.3.0.

**Comment by Gnimuc** [comment]
@rickhg12hs does this branch fix the problem?  if so, i'm going to tag it. https://github.com/JuliaGraphics/FreeType.jl/tree/backport-0.6

**Comment by rickhg12hs** [comment]
I'm wondering, do you want to bump the `BinaryProvider` version in `REQUIRE`?

**Comment by Gnimuc** [comment]
nope, I only corrected those URLs, no further changes were backported into this branch. the latest version of `BinaryProvider` that supports Julia-v0.6 is 0.3.3 which already works fine.

**Comment by rickhg12hs** [comment]
Hmmm, I guess I don't know how `REQUIRE` works.  For the `backport-0.6` branch, `REQUIRE` shows `
BinaryProvider 0.2.0`.

**Comment by Gnimuc** [comment]
it means the compatible version of `BinaryProvider` should >= 0.2.0 ;)

**Comment by Gnimuc** [comment]
I've tagged this branch, https://github.com/JuliaLang/METADATA.jl/pull/17956

**Comment by rickhg12hs** [comment]
> it means the compatible version of `BinaryProvider` should >= 0.2.0 ;)

> I've tagged this branch, [JuliaLang/METADATA.jl#17956](https://github.com/JuliaLang/METADATA.jl/pull/17956)


Ahhh, thanks!
