### ISSUE TITLE
FreeType will no longer work on Julia <1.3

### ISSUE THREAD

**Issue by asinghvi17** [JuliaGraphics/FreeType.jl#38]
Because the `deps/build.jl` script was removed, the FreeType binary no longer gets installed on any Julia version which doesn't support artifacts.  We can support those by re-adding the build script, and checking for the version at the start.

**Comment by SimonDanisch** [comment]
>Julia version which doesn't support artifacts

That's why we have: https://github.com/JuliaGraphics/FreeType.jl/blob/master/Project.toml#L11, no?

**Comment by ShalokShalom** [comment]
This can be closed?
